Update README.md
skills/hello-github-actions pull request #23
Opened 2022-10-25 17:45 UTC by svemu

I recently joined the GH actions team and followed the tutorial, found some super minor nitpicky inconsistencies in the instructions and hence proposing these changes

### Why:

Closes [issue link]

### What's being changed:

Proposing changes in Step 1 (Sub steps 4 and 7), Step 2( Sub step 3) 

### Check off the following:

- [ ] For workflow changes, I have verified the Actions workflows function as expected.
- [ ] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2022-11-21 02:45 UTC, bpires requested changes
Hey there @svemu! 👋🏻 

I'm a GitHub user and I've just done this skill course. I couldn't help to notice that you may have mixed up the buttons in the final text of your PR. Please accept these suggestions if adequate. Cheers!

2022-11-21 02:45 UTC, bpires commented on README.md
>  4. Type your commit message and commit your changes directly to your branch.
"Start commit" is actually right. This is the button we find in the top right of the workflow editor. There is no need for changes in item 3.

On the other hand, "Commit changes" is the button we will click on item 4, after typing the commit message. So, item 4 can be re-written for clarity:

```
4. Type your commit message and click **Commit changes** to commit your changes directly to your branch.
```

For quick check:

![image](https://user-images.githubusercontent.com/86871991/202951187-73dfebaf-a4b9-4fb8-80e0-8f98e1d78068.png)

2022-11-21 02:45 UTC, bpires commented on README.md
> +1. Navigate to the `.github/workflows/` folder, then select **Add file** and click on **+ New file**.
The correct button we would find is indeed "Create new file", not "+ New file".

In fact, the "Add file" label is hidden and pops up only on mouse hover.

IMHO, a better fix to make it clearer would be:

```
1. Navigate to the `.github/workflows/` folder, then select the "**+**" sign (Add file) on the top right and click on **Create new file**.
```

For quick check:

![image](https://user-images.githubusercontent.com/86871991/202951935-e576e22b-23f7-4236-b8eb-5ff7a19053fe.png)

2022-11-21 16:09 UTC, svemu reviewed
LGTM

2023-01-16 00:13 UTC, saifalsowaidi commented
UTC

2023-01-16 03:51 UTC, closed without merging