Create San.html
skills/hello-github-actions pull request #97
Opened 2024-12-04 07:14 UTC by sandeephc24

### Summary

### Changes

Closes:

### Task list

- [ ] For workflow changes, I have verified the Actions workflows function as expected.
- [ ] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2024-12-04 23:10 UTC, 12helvt12 commented
$ apktool d test.apk
I: Using Apktool 2.10.0 on test.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: 1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
$ apktool b test
I: Using Apktool 2.10.0 on test
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...

2024-12-05 09:06 UTC, jules-gd commented
Not merged...

2024-12-05 09:45 UTC, TheGiraffe3 requested changes
Did you mean to make this a Python script?
I don't think the code will work in html.

2024-12-23 19:59 UTC, AabedSagar approved these changes

2025-03-05 09:21 UTC, closed without merging